alt = "digital-forensics"

title = "ğŸ‘® Forensics"
description = "Evidence recovery of systems being compromised"

[ru]
title = "ğŸ‘® Ğ¤Ğ¾Ñ€ĞµĞ½Ğ·Ğ¸ĞºĞ°"
description = "ĞŸĞ¾Ğ¸ÑĞº Ğ´Ğ¾ĞºĞ°Ğ·Ğ°Ñ‚ĞµĞ»ÑŒÑÑ‚Ğ² ĞºĞ¾Ğ¼Ğ¿Ñ€Ğ¾Ğ¼ĞµÑ‚Ğ°Ñ†Ğ¸Ğ¸ ÑĞ¸ÑÑ‚ĞµĞ¼"