title = "ğŸ—ï¸ Infrastructure"
description = "Configuration and protection of IT-infrastructures"

[ru]
title = "ğŸ—ï¸ Ğ˜Ğ½Ñ„Ñ€Ğ°ÑÑ‚Ñ€ÑƒĞºÑ‚ÑƒÑ€Ğ°"
description = "ĞĞ°ÑÑ‚Ñ€Ğ¾Ğ¹ĞºĞ° Ğ¸ Ğ·Ğ°Ñ‰Ğ¸Ñ‚Ğ° Ğ˜Ğ¢-Ğ¸Ğ½Ñ„Ñ€Ğ°ÑÑ‚Ñ€ÑƒĞºÑ‚ÑƒÑ€Ñ‹"