title = "ğŸŒ Web"
description = "Interaction with browsers and web-servers"

[ru]
title = "ğŸŒ Ğ’ĞµĞ±"
description = "Ğ’Ğ·Ğ°Ğ¸Ğ¼Ğ¾Ğ´ĞµĞ¹ÑÑ‚Ğ²Ğ¸Ğµ Ñ Ğ±Ñ€Ğ°ÑƒĞ·ĞµÑ€Ğ°Ğ¼Ğ¸ Ğ¸ Ğ²ĞµĞ±-ÑĞµÑ€Ğ²ĞµÑ€Ğ°Ğ¼Ğ¸"